# Netlify Configuration File
# Read more at: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Since index.html is in the backend/ directory, and we don't have a build step (zero build/zero npm),
  # we tell Netlify to publish the backend/ directory directly to serve index.html.
  publish = "sql-lineage-visualizer/backend"
